service: notesAPI
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: philip-aws
  region: eu-north-1
  iam: 
    role: arn:aws:iam::724806840307:role/lectures-cloud

plugins:
  - serverless-webpack

package:
  individually: true


functions:
  getNotes:
    handler: functions/getNotes/index.handler
    events:
      - httpApi:
          path: "/notes"
          method: GET
  postNotes:
    handler: functions/postNotes/index.handler
    events:
      - httpApi:
          path: "/notes"
          method: POST
  updateNotes:
    handler: functions/updateNotes/index.handler
    events:
      - httpApi:
          path: "/notes/{noteId}"
          method: PUT
  deleteNotes:
    handler: functions/deleteNotes/index.handler
    events:
      - httpApi:
          path: "/notes/{noteId}"
          method: DELETE
  signUp:
    handler: functions/signUp/index.handler
    events:
      - httpApi:
          path: "/auth/signup"
          method: POST
  login:
    handler: functions/login/index.handler
    events:
      - httpApi:
          path: "/auth/login"
          method: POST           


resources:
  Resources:
    notesDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notesAPI
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    noteusersDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: noteaccounts
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
